# Generated by Django 4.2.7 on 2023-12-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account_manager", "0004_blogpost_delete_blog_delete_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="draft",
            field=models.BooleanField(default=False),
        ),
    ]
